apiVersion: v1
kind: ConfigMap
metadata:
  name: nvmeof-csi-config
  namespace: kube-system
data: # TODO- change it to be dynamic depending on the cluster
  config.json: |-
    {
      "nodes": [
        {
          "name": "nvmeof-gateway-node",
          "grpcAddress": "10.242.64.32:5500", 
          "targetType": "nvme-tcp",
          "targetAddr": "10.242.64.32",
          "targetPort": 4420
        }
      ]
    }
