# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nvmeof-csi-sc
provisioner: csi.nvmeof.io
parameters:
  fsType: ext4
  RbdPoolName: "mypool" # TODO- change it to be dynamic
  SubsystemNqn: "nqn.2016-06.io.spdk:cnode1.mygroup1" # TODO- change it to be dynamic
  traddr: "10.242.64.32" # TODO- change it to be dynamic depending on the cluster
  trsvcid: "4420"
  transport: "tcp"
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true  # Added for resize support